version: '3.8'

services:

  api-test:
    build:
      context: .
      dockerfile: docker/node-Dockerfile
    command: sh -c "npm run migrate && npm run seed && npm run test"
    depends_on:
      - 'postgres-test'
    environment:
      NODE_ENV: "test"
      POSTGRES_HOST: postgres-test
    ports:
      - '5001:5000'
    volumes:
      - '.:/app'
      - '/app/node_modules'

  postgres-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - .env
    ports:
      - '5437:5432'
